## File generated by the BNF Converter (bnfc 2.9.5).

CC = gcc -g
CCFLAGS = --ansi -W -Wall -Wsign-conversion -Wno-unused-parameter -Wno-unused-function -Wno-unneeded-internal-declaration ${CC_OPTS}

FLEX = flex
FLEX_OPTS = -Pcodigo_

BISON = bison
BISON_OPTS = -t -pcodigo_

OBJS = Absyn.o Buffer.o Lexer.o Parser.o Printer.o Skeleton.o

.PHONY : clean distclean

all : Testcodigo

clean :
	rm -f *.o Testcodigo codigo.aux codigo.log codigo.pdf codigo.dvi codigo.ps codigo

distclean : clean
	rm -f Absyn.h Absyn.c Bison.h Buffer.h Buffer.c codigo.l Lexer.c codigo.y Parser.h Parser.c Printer.c Printer.h Skeleton.c Skeleton.h Test.c Makefile codigo.tex

Testcodigo : ${OBJS} Test.o
	@echo "Linking Testcodigo..."
	${CC} ${OBJS} Test.o -o Testcodigo

Absyn.o : Absyn.c Absyn.h
	${CC} ${CCFLAGS} -c Absyn.c

Buffer.o : Buffer.c Buffer.h
	${CC} ${CCFLAGS} -c Buffer.c

Lexer.c : codigo.l
	${FLEX} ${FLEX_OPTS} -oLexer.c codigo.l

Parser.c Bison.h : codigo.y
	${BISON} ${BISON_OPTS} codigo.y -o Parser.c

Lexer.o : CCFLAGS+=-Wno-sign-conversion

Lexer.o : Lexer.c Bison.h
	${CC} ${CCFLAGS} -c Lexer.c

Parser.o : Parser.c Absyn.h Bison.h
	${CC} ${CCFLAGS} -c Parser.c

Printer.o : Printer.c Printer.h Absyn.h
	${CC} ${CCFLAGS} -c Printer.c

Test.o : Test.c Parser.h Printer.h Absyn.h
	${CC} ${CCFLAGS} -c Test.c

Skeleton.o : Skeleton.c Parser.h Printer.h Absyn.h
	${CC} ${CCFLAGS} -c Skeleton.c
